# PHASE 1

# Data Collection/preparation part.

In [22]:
#Importing necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

#  1. Literacy Rate in each state

Sources: https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate
         https://www.indiabudget.gov.in/economicsurvey/doc/stat/tab85.pdf

* We have Literacy rate for each states for year 2001 and 2011 as per census data provided by our government.
* Comparing the years 2001 and 2011 literacy rates, I have filled up the litearcy rate for all years, by finding the rate of increase in literacy for each state.
* Literacy rate of all states have been increased from 2001 to 2012.

In [4]:
df_lit = pd.read_excel("Literacy_Rate_2001_to_2012.xlsx")
df_lit

,STATE/UT,2001 Literacy Rate (%),2002 Literacy Rate (%),2003 Literacy Rate (%),2004 Literacy Rate (%),2005 Literacy Rate (%),2006 Literacy Rate (%),2007 Literacy Rate (%),2008 Literacy Rate (%),2009 Literacy Rate (%),2010 Literacy Rate (%),2011 Literacy Rate (%),2012 Literacy Rate (%)
0,ANDAMAN & NICOBAR ISLANDS,81.18,81.689,82.198,82.707,83.216,83.725,84.234,84.743,85.252,85.761,86.27,86.779
1,ANDHRA PRADESH,60.47,61.189,61.908,62.627,63.346,64.065,64.784,65.503,66.222,66.941,67.66,63.379
2,ARUNACHAL PRADESH,54.74,55.962,57.184,58.406,59.628,60.850,62.072,63.294,64.516,65.738,66.95,68.180
3,ASSAM,63.25,64.144,65.038,65.932,66.826,67.720,68.614,69.508,70.402,71.296,72.19,73.084
4,BIHAR,47.00,48.682,50.364,52.046,53.728,55.410,57.092,58.774,60.456,62.138,63.82,65.502
5,CHANDIGARH,76.57,77.518,78.466,79.414,80.362,81.310,82.258,83.206,84.154,85.102,86.05,86.998
6,CHHATTISGARH,65.18,65.690,66.200,66.710,67.220,67.730,68.240,68.750,69.260,69.770,70.28,70.790
7,DADRA & NAGAR HAVELI,57.63,59.632,61.634,63.636,65.638,67.640,69.642,71.644,73.646,75.648,77.65,79.652
8,DAMAN & DIU,78.18,79.069,79.958,80.847,81.736,82.625,83.514,84.403,85.292,86.181,87.07,87.959
9,GOA,82.01,82.679,83.348,84.017,84.686,85.355,86.024,86.693,87.362,88.031,88.70,89.369
10,GUJARAT,69.14,70.157,71.174,72.191,73.208,74.225,75.242,76.259,77.276,78.293,79.31,80.327
11,HARYANA,67.91,68.783,69.656,70.529,71.402,72.275,73.148,74.021,74.894,75.767,76.64,77.509
12,HIMACHAL PRADESH,76.48,77.112,77.744,78.376,79.008,79.640,80.272,80.904,81.536,82.168,82.80,83.432
13,JAMMU & KASHMIR,55.52,56.842,58.164,59.486,60.808,62.130,63.452,64.774,66.096,67.418,68.74,70.062
14,JHARKHAND,53.56,54.845,56.130,57.415,58.700,59.985,61.270,62.555,63.840,65.125,66.41,67.695
15,KARNATAKA,67.04,67.896,68.752,69.608,70.464,71.320,72.176,73.032,73.888,74.744,75.60,76.456
16,KERALA,90.86,91.165,91.470,91.775,92.080,92.385,92.690,92.995,93.300,93.605,93.91,94.215
17,LAKSHADWEEP,87.52,87.996,88.472,88.948,89.424,89.900,90.376,90.852,91.328,91.804,92.28,92.756
18,MADHYA PRADESH,63.74,64.429,65.118,65.807,66.496,67.185,67.874,68.563,69.252,69.941,70.63,71.319
19,MAHARASHTRA,76.88,77.426,77.972,78.518,79.064,79.610,80.156,80.702,81.248,81.794,82.34,82.886
20,MANIPUR,61.00,62.885,64.770,66.655,68.540,70.425,72.310,74.195,76.080,77.965,79.85,81.735
21,MEGHALAYA,62.56,63.747,64.934,66.121,67.308,68.495,69.682,70.869,72.056,73.243,74.43,75.617
22,MIZORAM,88.80,89.078,89.356,89.634,89.912,90.190,90.468,90.746,91.024,91.302,91.58,91.858
23,NAGALAND,66.59,67.886,69.182,70.478,71.774,73.070,74.366,75.662,76.958,78.254,79.55,80.846
24,NCT OF DELHI,81.67,82.137,82.604,83.071,83.538,84.005,84.472,84.939,85.406,85.873,86.34,86.807
25,ODISHA,63.61,64.536,65.462,66.388,67.314,68.240,69.166,70.092,71.018,71.944,72.87,73.796
26,PUDUCHERRY,81.24,81.771,82.302,82.833,83.364,83.895,84.426,84.957,85.488,86.019,86.55,87.081
27,PUNJAB,69.65,70.269,70.888,71.507,72.126,72.745,73.364,73.983,74.602,75.221,75.84,76.459
28,RAJASTHAN,60.41,60.980,61.550,62.120,62.690,63.260,63.830,64.400,64.970,65.540,66.11,66.680
29,SIKKIM,68.81,70.149,71.488,72.827,74.166,75.505,76.844,78.183,79.522,80.861,82.20,83.539
30,TAMIL NADU,73.47,74.156,74.842,75.528,76.214,76.900,77.586,78.272,78.958,79.644,80.33,81.016
31,TRIPURA,73.19,74.646,76.102,77.558,79.014,80.470,81.926,83.382,84.838,86.294,87.75,89.206
32,UTTAR PRADESH,57.36,58.596,59.832,61.068,62.304,63.540,64.776,66.012,67.248,68.484,69.72,70.956
33,UTTARAKHAND,71.62,72.340,73.060,73.780,74.500,75.220,75.940,76.660,77.380,78.100,78.82,79.540
34,WEST BENGAL,68.64,69.484,70.328,71.172,72.016,72.860,73.704,74.548,75.392,76.236,77.08,77.924

#  2. The population of each state.

Sources: http://cyberjournalist.org.in/census/cenindia.html
        https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population

* We have population information for each states for year 2001 and 2011 as per census data provided by our government.
* Comparing the years 2001 and 2011 population variation, I have filled up the population for all years, by finding the rate of increase/decrease in population for each state.
* Population rate of all states have been increased from 2001 to 2011 except NAGALAND.

In [23]:
df_pop = pd.read_excel("Population_2001_to_2012_statewise.xlsx")
df_pop

,STATE/UT,2001_Population,2002_Population,2003_Population,2004_Population,2005_Population,2006_Population,2007_Population,2008_Population,2009_Population,2010_Population,2011_Population,2012_Population
0,ANDAMAN & NICOBAR ISLANDS,356265,358696.6,361128.2,363559.8,365991.4,368423.0,370854.6,373286.2,375717.8,378149.4,380581,383012.6
1,ANDHRA PRADESH,75727541,76612864.6,77498188.2,78383511.8,79268835.4,80154159.0,81039482.6,81924806.2,82810129.8,83695453.4,84580777,85466100.6
2,ARUNACHAL PRADESH,1091117,1120378.0,1149639.0,1178900.0,1208161.0,1237422.0,1266683.0,1295944.0,1325205.0,1354466.0,1383727,1412988.0
3,ASSAM,26638407,27095123.9,27551840.8,28008557.7,28465274.6,28921991.5,29378708.4,29835425.3,30292142.2,30748859.1,31205576,31662292.9
4,BIHAR,82878796,85000861.6,87122927.2,89244992.8,91367058.4,93489124.0,95611189.6,97733255.2,99855320.8,101977386.4,104099452,106221518.0
5,CHANDIGARH,900914,916367.6,931821.2,947274.8,962728.4,978182.0,993635.6,1009089.2,1024542.8,1039996.4,1055450,1070903.6
6,CHHATTISGARH,20795956,21270880.2,21745804.4,22220728.6,22695652.8,23170577.0,23645501.2,24120425.4,24595349.6,25070273.8,25545198,26020122.2
7,DADRA & NAGAR HAVELI,220451,232776.8,245102.6,257428.4,269754.2,282080.0,294405.8,306731.6,319057.4,331383.2,343709,356034.8
8,DAMAN & DIU,158059,166577.8,175096.6,183615.4,192134.2,200653.0,209171.8,217690.6,226209.4,234728.2,243247,251765.8
9,GOA,1343998,1355452.7,1366907.4,1378362.1,1389816.8,1401271.5,1412726.2,1424180.9,1435635.6,1447090.3,1458545,1469996.7
10,GUJARAT,50596992,51581262.0,52565532.0,53549802.0,54534072.0,55518342.0,56502612.0,57486882.0,58471152.0,59455422.0,60439692,61423962.0
11,HARYANA,21082989,21509836.3,21936683.6,22363530.9,22790378.2,23217225.5,23644072.8,24070920.1,24497767.4,24924614.7,25351462,25778309.3
12,HIMACHAL PRADESH,6077248,6155983.4,6234718.8,6313454.2,6392189.6,6470925.0,6549660.4,6628395.8,6707131.2,6785866.6,6864602,6943337.4
13,JAMMU & KASHMIR,10069917,10317055.5,10564194.0,10811332.5,11058471.0,11305609.5,11552748.0,11799886.5,12047025.0,12294163.5,12541302,12788440.5
14,JHARKHAND,26909428,27517298.6,28125169.2,28733039.8,29340910.4,29948781.0,30556651.6,31164522.2,31772392.8,32380263.4,32988134,33596004.6
15,KARNATAKA,52733958,53570091.9,54406225.8,55242359.7,56078493.6,56914627.5,57750761.4,58586895.3,59423029.2,60259163.1,61095297,61931430.9
16,KERALA,31838619,31995363.2,32152107.4,32308851.6,32465595.8,32622340.0,32779084.2,32935828.4,33092572.6,33249316.8,33406061,33562805.2
17,LAKSHADWEEP,60595,60982.8,61370.6,61758.4,62146.2,62534.0,62921.8,63309.6,63697.4,64085.2,64473,64860.8
18,MADHYA PRADESH,60385118,61609287.1,62833456.2,64057625.3,65281794.4,66505963.5,67730132.6,68954301.7,70178470.8,71402639.9,72626809,73850978.1
19,MAHARASHTRA,96752247,98314455.6,99876664.2,101438872.8,103001081.4,104563290.0,106125498.6,107687707.2,109249915.8,110812124.4,112374333,113936542.0
20,MANIPUR,2388634,2435350.0,2482066.0,2528782.0,2575498.0,2622214.0,2668930.0,2715646.0,2762362.0,2809078.0,2855794,2902510.0
21,MEGHALAYA,2306069,2372151.0,2438233.0,2504315.0,2570397.0,2636479.0,2702561.0,2768643.0,2834725.0,2900807.0,2966889,3032971.0
22,MIZORAM,891058,911672.8,932287.6,952902.4,973517.2,994132.0,1014746.8,1035361.6,1055976.4,1076591.2,1097206,1117820.8
23,NAGALAND,1988636,1987622.6,1986609.2,1985595.8,1984582.4,1983569.0,1982555.6,1981542.2,1980528.8,1979515.4,1978502,1977488.6
24,NCT OF DELHI,13782976,14083472.5,14383969.0,14684465.5,14984962.0,15285458.5,15585955.0,15886451.5,16186948.0,16487444.5,16787941,17088437.5
25,ODISHA,36706920,37233649.8,37760379.6,38287109.4,38813839.2,39340569.0,39867298.8,40394028.6,40920758.4,41447488.2,41974218,42500947.8
26,PUDUCHERRY,973829,1001241.4,1028653.8,1056066.2,1083478.6,1110891.0,1138303.4,1165715.8,1193128.2,1220540.6,1247953,1275365.4
27,PUNJAB,24289296,24634700.2,24980104.4,25325508.6,25670912.8,26016317.0,26361721.2,26707125.4,27052529.6,27397933.8,27743338,28088742.2
28,RAJASTHAN,56473122,57680653.5,58888185.0,60095716.5,61303248.0,62510779.5,63718311.0,64925842.5,66133374.0,67340905.5,68548437,69755968.5
29,SIKKIM,540493,547501.4,554509.8,561518.2,568526.6,575535.0,582543.4,589551.8,596560.2,603568.6,610577,617585.4
30,TAMIL NADU,62110839,63114458.1,64118077.2,65121696.3,66125315.4,67128934.5,68132553.6,69136172.7,70139791.8,71143410.9,72147030,73150649.1
31,TRIPURA,3191168,3239442.9,3287717.8,3335992.7,3384267.6,3432542.5,3480817.4,3529092.3,3577367.2,3625642.1,3673917,3722191.9
32,UTTAR PRADESH,166052859,169428807.2,172804755.4,176180703.6,179556651.8,182932600.0,186308548.2,189684496.4,193060444.6,196436392.8,199812341,203188289.0
33,UTTARAKHAND,8479562,8640235.0,8800908.0,8961581.0,9122254.0,9282927.0,9443600.0,9604273.0,9764946.0,9925619.0,10086292,10246965.0
34,WEST BENGAL,80221171,81326665.4,82432159.8,83537654.2,84643148.6,85748643.0,86854137.4,87959631.8,89065126.2,90170620.6,91276115,92381609.4

In [11]:
df_pop.columns

Index(['STATE/UT', '2001_Population', '2002_Population', '2003_Population',
       '2004_Population', '2005_Population', '2006_Population',
       '2007_Population', '2008_Population', '2009_Population',
       '2010_Population', '2011_Population', '2012_Population'],
      dtype='object')

In [24]:
df_pop.dtypes

STATE/UT            object
2001_Population      int64
2002_Population    float64
2003_Population    float64
2004_Population    float64
2005_Population    float64
2006_Population    float64
2007_Population    float64
2008_Population    float64
2009_Population    float64
2010_Population    float64
2011_Population      int64
2012_Population    float64
dtype: object

In [25]:
#Changing datatypes of Population, since it cannot be in decimal.

df_pop['2002_Population']= df_pop['2002_Population'].astype(int)
df_pop['2003_Population']= df_pop['2003_Population'].astype(int)
df_pop['2004_Population']= df_pop['2004_Population'].astype(int)
df_pop['2005_Population']= df_pop['2005_Population'].astype(int)
df_pop['2006_Population']= df_pop['2006_Population'].astype(int)
df_pop['2007_Population']= df_pop['2007_Population'].astype(int)
df_pop['2008_Population']= df_pop['2008_Population'].astype(int)
df_pop['2009_Population']= df_pop['2009_Population'].astype(int)
df_pop['2010_Population']= df_pop['2010_Population'].astype(int)
df_pop['2012_Population']= df_pop['2012_Population'].astype(int)

In [26]:
df_pop.head()

,STATE/UT,2001_Population,2002_Population,2003_Population,2004_Population,2005_Population,2006_Population,2007_Population,2008_Population,2009_Population,2010_Population,2011_Population,2012_Population
0,ANDAMAN & NICOBAR ISLANDS,356265,358696,361128,363559,365991,368422,370854,373286,375717,378149,380581,383012
1,ANDHRA PRADESH,75727541,76612864,77498188,78383511,79268835,80154158,81039482,81924806,82810129,83695453,84580777,85466100
2,ARUNACHAL PRADESH,1091117,1120378,1149639,1178900,1208161,1237422,1266683,1295944,1325205,1354466,1383727,1412988
3,ASSAM,26638407,27095123,27551840,28008557,28465274,28921991,29378708,29835425,30292142,30748859,31205576,31662292
4,BIHAR,82878796,85000861,87122927,89244992,91367058,93489123,95611189,97733255,99855320,101977386,104099452,106221518

# 3. Area of each state

Sources: https://statisticstimes.com/geography/india/indian-states-area.php

In [27]:
df_area= pd.read_excel("Area_statewise.xlsx")
df_area

                     STATE/UT  Area (in square kilometers)
0   ANDAMAN & NICOBAR ISLANDS                         8249
1              ANDHRA PRADESH                       275025
2           ARUNACHAL PRADESH                        83743
3                       ASSAM                        78438
4                       BIHAR                        94163
5                  CHANDIGARH                          114
6                CHHATTISGARH                       135192
7        DADRA & NAGAR HAVELI                          491
8                 DAMAN & DIU                          112
9                NCT OF DELHI                         1483
10                        GOA                         3702
11                    GUJARAT                       196244
12                    HARYANA                        44212
13           HIMACHAL PRADESH                        55673
14            JAMMU & KASHMIR                       222236
15                  JHARKHAND                        79714
16                  KARNATAKA                       191791
17                     KERALA                        38863
18                LAKSHADWEEP                           32
19             MADHYA PRADESH                       308245
20                MAHARASHTRA                       307713
21                    MANIPUR                        22327
22                  MEGHALAYA                        22429
23                    MIZORAM                        21081
24                   NAGALAND                        16579
25                     ODISHA                       155707
26                 PUDUCHERRY                          479
27                     PUNJAB                        50362
28                  RAJASTHAN                       342239
29                     SIKKIM                         7096
30                 TAMIL NADU                       130058
31                    TRIPURA                        10491
32              UTTAR PRADESH                       240928
33                UTTARAKHAND                        53483
34                WEST BENGAL                        88752

Merging all datas

In [29]:
df_merge = df_lit.merge(df_pop, on='STATE/UT', how='inner')
df_merge

,STATE/UT,2001 Literacy Rate (%),2002 Literacy Rate (%),2003 Literacy Rate (%),2004 Literacy Rate (%),2005 Literacy Rate (%),2006 Literacy Rate (%),2007 Literacy Rate (%),2008 Literacy Rate (%),2009 Literacy Rate (%),...,2003_Population,2004_Population,2005_Population,2006_Population,2007_Population,2008_Population,2009_Population,2010_Population,2011_Population,2012_Population
0,ANDAMAN & NICOBAR ISLANDS,81.18,81.689,82.198,82.707,83.216,83.725,84.234,84.743,85.252,...,361128,363559,365991,368422,370854,373286,375717,378149,380581,383012
1,ANDHRA PRADESH,60.47,61.189,61.908,62.627,63.346,64.065,64.784,65.503,66.222,...,77498188,78383511,79268835,80154158,81039482,81924806,82810129,83695453,84580777,85466100
2,ARUNACHAL PRADESH,54.74,55.962,57.184,58.406,59.628,60.850,62.072,63.294,64.516,...,1149639,1178900,1208161,1237422,1266683,1295944,1325205,1354466,1383727,1412988
3,ASSAM,63.25,64.144,65.038,65.932,66.826,67.720,68.614,69.508,70.402,...,27551840,28008557,28465274,28921991,29378708,29835425,30292142,30748859,31205576,31662292
4,BIHAR,47.00,48.682,50.364,52.046,53.728,55.410,57.092,58.774,60.456,...,87122927,89244992,91367058,93489123,95611189,97733255,99855320,101977386,104099452,106221518
5,CHANDIGARH,76.57,77.518,78.466,79.414,80.362,81.310,82.258,83.206,84.154,...,931821,947274,962728,978181,993635,1009089,1024542,1039996,1055450,1070903
6,CHHATTISGARH,65.18,65.690,66.200,66.710,67.220,67.730,68.240,68.750,69.260,...,21745804,22220728,22695652,23170576,23645501,24120425,24595349,25070273,25545198,26020122
7,DADRA & NAGAR HAVELI,57.63,59.632,61.634,63.636,65.638,67.640,69.642,71.644,73.646,...,245102,257428,269754,282079,294405,306731,319057,331383,343709,356034
8,DAMAN & DIU,78.18,79.069,79.958,80.847,81.736,82.625,83.514,84.403,85.292,...,175096,183615,192134,200652,209171,217690,226209,234728,243247,251765
9,GOA,82.01,82.679,83.348,84.017,84.686,85.355,86.024,86.693,87.362,...,1366907,1378362,1389816,1401271,1412726,1424180,1435635,1447090,1458545,1469996
10,GUJARAT,69.14,70.157,71.174,72.191,73.208,74.225,75.242,76.259,77.276,...,52565532,53549802,54534072,55518342,56502612,57486882,58471152,59455422,60439692,61423962
11,HARYANA,67.91,68.783,69.656,70.529,71.402,72.275,73.148,74.021,74.894,...,21936683,22363530,22790378,23217225,23644072,24070920,24497767,24924614,25351462,25778309
12,HIMACHAL PRADESH,76.48,77.112,77.744,78.376,79.008,79.640,80.272,80.904,81.536,...,6234718,6313454,6392189,6470925,6549660,6628395,6707131,6785866,6864602,6943337
13,JAMMU & KASHMIR,55.52,56.842,58.164,59.486,60.808,62.130,63.452,64.774,66.096,...,10564194,10811332,11058471,11305609,11552748,11799886,12047025,12294163,12541302,12788440
14,JHARKHAND,53.56,54.845,56.130,57.415,58.700,59.985,61.270,62.555,63.840,...,28125169,28733039,29340910,29948781,30556651,31164522,31772392,32380263,32988134,33596004
15,KARNATAKA,67.04,67.896,68.752,69.608,70.464,71.320,72.176,73.032,73.888,...,54406225,55242359,56078493,56914627,57750761,58586895,59423029,60259163,61095297,61931430
16,KERALA,90.86,91.165,91.470,91.775,92.080,92.385,92.690,92.995,93.300,...,32152107,32308851,32465595,32622339,32779084,32935828,33092572,33249316,33406061,33562805
17,LAKSHADWEEP,87.52,87.996,88.472,88.948,89.424,89.900,90.376,90.852,91.328,...,61370,61758,62146,62534,62921,63309,63697,64085,64473,64860
18,MADHYA PRADESH,63.74,64.429,65.118,65.807,66.496,67.185,67.874,68.563,69.252,...,62833456,64057625,65281794,66505963,67730132,68954301,70178470,71402639,72626809,73850978
19,MAHARASHTRA,76.88,77.426,77.972,78.518,79.064,79.610,80.156,80.702,81.248,...,99876664,101438872,103001081,104563289,106125498,107687707,109249915,110812124,112374333,113936542
20,MANIPUR,61.00,62.885,64.770,66.655,68.540,70.425,72.310,74.195,76.080,...,2482066,2528782,2575498,2622214,2668930,2715646,2762362,2809078,2855794,2902510
21,MEGHALAYA,62.56,63.747,64.934,66.121,67.308,68.495,69.682,70.869,72.056,...,2438233,2504315,2570397,2636479,2702561,2768643,2834725,2900807,2966889,3032971
22,MIZORAM,88.80,89.078,89.356,89.634,89.912,90.190,90.468,90.746,91.024,...,932287,952902,973517,994132,1014746,1035361,1055976,1076591,1097206,1117820
23,NAGALAND,66.59,67.886,69.182,70.478,71.774,73.070,74.366,75.662,76.958,...,1986609,1985595,1984582,1983569,1982555,1981542,1980528,1979515,1978502,1977488
24,NCT OF DELHI,81.67,82.137,82.604,83.071,83.538,84.005,84.472,84.939,85.406,...,14383969,14684465,14984962,15285458,15585955,15886451,16186948,16487444,16787941,17088437
25,ODISHA,63.61,64.536,65.462,66.388,67.314,68.240,69.166,70.092,71.018,...,37760379,38287109,38813839,39340568,39867298,40394028,40920758,41447488,41974218,42500947
26,PUDUCHERRY,81.24,81.771,82.302,82.833,83.364,83.895,84.426,84.957,85.488,...,1028653,1056066,1083478,1110890,1138303,1165715,1193128,1220540,1247953,1275365
27,PUNJAB,69.65,70.269,70.888,71.507,72.126,72.745,73.364,73.983,74.602,...,24980104,25325508,25670912,26016316,26361721,26707125,27052529,27397933,27743338,28088742
28,RAJASTHAN,60.41,60.980,61.550,62.120,62.690,63.260,63.830,64.400,64.970,...,58888185,60095716,61303248,62510779,63718311,64925842,66133374,67340905,68548437,69755968
29,SIKKIM,68.81,70.149,71.488,72.827,74.166,75.505,76.844,78.183,79.522,...,554509,561518,568526,575535,582543,589551,596560,603568,610577,617585
30,TAMIL NADU,73.47,74.156,74.842,75.528,76.214,76.900,77.586,78.272,78.958,...,64118077,65121696,66125315,67128934,68132553,69136172,70139791,71143410,72147030,73150649
31,TRIPURA,73.19,74.646,76.102,77.558,79.014,80.470,81.926,83.382,84.838,...,3287717,3335992,3384267,3432542,3480817,3529092,3577367,3625642,3673917,3722191
32,UTTAR PRADESH,57.36,58.596,59.832,61.068,62.304,63.540,64.776,66.012,67.248,...,172804755,176180703,179556651,182932599,186308548,189684496,193060444,196436392,199812341,203188289
33,UTTARAKHAND,71.62,72.340,73.060,73.780,74.500,75.220,75.940,76.660,77.380,...,8800908,8961581,9122254,9282927,9443600,9604273,9764946,9925619,10086292,10246965
34,WEST BENGAL,68.64,69.484,70.328,71.172,72.016,72.860,73.704,74.548,75.392,...,82432159,83537654,84643148,85748643,86854137,87959631,89065126,90170620,91276115,92381609

In [30]:
df_stats= df_merge.merge(df_area, on='STATE/UT', how='inner')
df_stats

,STATE/UT,2001 Literacy Rate (%),2002 Literacy Rate (%),2003 Literacy Rate (%),2004 Literacy Rate (%),2005 Literacy Rate (%),2006 Literacy Rate (%),2007 Literacy Rate (%),2008 Literacy Rate (%),2009 Literacy Rate (%),...,2004_Population,2005_Population,2006_Population,2007_Population,2008_Population,2009_Population,2010_Population,2011_Population,2012_Population,Area (in square kilometers)
0,ANDAMAN & NICOBAR ISLANDS,81.18,81.689,82.198,82.707,83.216,83.725,84.234,84.743,85.252,...,363559,365991,368422,370854,373286,375717,378149,380581,383012,8249
1,ANDHRA PRADESH,60.47,61.189,61.908,62.627,63.346,64.065,64.784,65.503,66.222,...,78383511,79268835,80154158,81039482,81924806,82810129,83695453,84580777,85466100,275025
2,ARUNACHAL PRADESH,54.74,55.962,57.184,58.406,59.628,60.850,62.072,63.294,64.516,...,1178900,1208161,1237422,1266683,1295944,1325205,1354466,1383727,1412988,83743
3,ASSAM,63.25,64.144,65.038,65.932,66.826,67.720,68.614,69.508,70.402,...,28008557,28465274,28921991,29378708,29835425,30292142,30748859,31205576,31662292,78438
4,BIHAR,47.00,48.682,50.364,52.046,53.728,55.410,57.092,58.774,60.456,...,89244992,91367058,93489123,95611189,97733255,99855320,101977386,104099452,106221518,94163
5,CHANDIGARH,76.57,77.518,78.466,79.414,80.362,81.310,82.258,83.206,84.154,...,947274,962728,978181,993635,1009089,1024542,1039996,1055450,1070903,114
6,CHHATTISGARH,65.18,65.690,66.200,66.710,67.220,67.730,68.240,68.750,69.260,...,22220728,22695652,23170576,23645501,24120425,24595349,25070273,25545198,26020122,135192
7,DADRA & NAGAR HAVELI,57.63,59.632,61.634,63.636,65.638,67.640,69.642,71.644,73.646,...,257428,269754,282079,294405,306731,319057,331383,343709,356034,491
8,DAMAN & DIU,78.18,79.069,79.958,80.847,81.736,82.625,83.514,84.403,85.292,...,183615,192134,200652,209171,217690,226209,234728,243247,251765,112
9,GOA,82.01,82.679,83.348,84.017,84.686,85.355,86.024,86.693,87.362,...,1378362,1389816,1401271,1412726,1424180,1435635,1447090,1458545,1469996,3702
10,GUJARAT,69.14,70.157,71.174,72.191,73.208,74.225,75.242,76.259,77.276,...,53549802,54534072,55518342,56502612,57486882,58471152,59455422,60439692,61423962,196244
11,HARYANA,67.91,68.783,69.656,70.529,71.402,72.275,73.148,74.021,74.894,...,22363530,22790378,23217225,23644072,24070920,24497767,24924614,25351462,25778309,44212
12,HIMACHAL PRADESH,76.48,77.112,77.744,78.376,79.008,79.640,80.272,80.904,81.536,...,6313454,6392189,6470925,6549660,6628395,6707131,6785866,6864602,6943337,55673
13,JAMMU & KASHMIR,55.52,56.842,58.164,59.486,60.808,62.130,63.452,64.774,66.096,...,10811332,11058471,11305609,11552748,11799886,12047025,12294163,12541302,12788440,222236
14,JHARKHAND,53.56,54.845,56.130,57.415,58.700,59.985,61.270,62.555,63.840,...,28733039,29340910,29948781,30556651,31164522,31772392,32380263,32988134,33596004,79714
15,KARNATAKA,67.04,67.896,68.752,69.608,70.464,71.320,72.176,73.032,73.888,...,55242359,56078493,56914627,57750761,58586895,59423029,60259163,61095297,61931430,191791
16,KERALA,90.86,91.165,91.470,91.775,92.080,92.385,92.690,92.995,93.300,...,32308851,32465595,32622339,32779084,32935828,33092572,33249316,33406061,33562805,38863
17,LAKSHADWEEP,87.52,87.996,88.472,88.948,89.424,89.900,90.376,90.852,91.328,...,61758,62146,62534,62921,63309,63697,64085,64473,64860,32
18,MADHYA PRADESH,63.74,64.429,65.118,65.807,66.496,67.185,67.874,68.563,69.252,...,64057625,65281794,66505963,67730132,68954301,70178470,71402639,72626809,73850978,308245
19,MAHARASHTRA,76.88,77.426,77.972,78.518,79.064,79.610,80.156,80.702,81.248,...,101438872,103001081,104563289,106125498,107687707,109249915,110812124,112374333,113936542,307713
20,MANIPUR,61.00,62.885,64.770,66.655,68.540,70.425,72.310,74.195,76.080,...,2528782,2575498,2622214,2668930,2715646,2762362,2809078,2855794,2902510,22327
21,MEGHALAYA,62.56,63.747,64.934,66.121,67.308,68.495,69.682,70.869,72.056,...,2504315,2570397,2636479,2702561,2768643,2834725,2900807,2966889,3032971,22429
22,MIZORAM,88.80,89.078,89.356,89.634,89.912,90.190,90.468,90.746,91.024,...,952902,973517,994132,1014746,1035361,1055976,1076591,1097206,1117820,21081
23,NAGALAND,66.59,67.886,69.182,70.478,71.774,73.070,74.366,75.662,76.958,...,1985595,1984582,1983569,1982555,1981542,1980528,1979515,1978502,1977488,16579
24,NCT OF DELHI,81.67,82.137,82.604,83.071,83.538,84.005,84.472,84.939,85.406,...,14684465,14984962,15285458,15585955,15886451,16186948,16487444,16787941,17088437,1483
25,ODISHA,63.61,64.536,65.462,66.388,67.314,68.240,69.166,70.092,71.018,...,38287109,38813839,39340568,39867298,40394028,40920758,41447488,41974218,42500947,155707
26,PUDUCHERRY,81.24,81.771,82.302,82.833,83.364,83.895,84.426,84.957,85.488,...,1056066,1083478,1110890,1138303,1165715,1193128,1220540,1247953,1275365,479
27,PUNJAB,69.65,70.269,70.888,71.507,72.126,72.745,73.364,73.983,74.602,...,25325508,25670912,26016316,26361721,26707125,27052529,27397933,27743338,28088742,50362
28,RAJASTHAN,60.41,60.980,61.550,62.120,62.690,63.260,63.830,64.400,64.970,...,60095716,61303248,62510779,63718311,64925842,66133374,67340905,68548437,69755968,342239
29,SIKKIM,68.81,70.149,71.488,72.827,74.166,75.505,76.844,78.183,79.522,...,561518,568526,575535,582543,589551,596560,603568,610577,617585,7096
30,TAMIL NADU,73.47,74.156,74.842,75.528,76.214,76.900,77.586,78.272,78.958,...,65121696,66125315,67128934,68132553,69136172,70139791,71143410,72147030,73150649,130058
31,TRIPURA,73.19,74.646,76.102,77.558,79.014,80.470,81.926,83.382,84.838,...,3335992,3384267,3432542,3480817,3529092,3577367,3625642,3673917,3722191,10491
32,UTTAR PRADESH,57.36,58.596,59.832,61.068,62.304,63.540,64.776,66.012,67.248,...,176180703,179556651,182932599,186308548,189684496,193060444,196436392,199812341,203188289,240928
33,UTTARAKHAND,71.62,72.340,73.060,73.780,74.500,75.220,75.940,76.660,77.380,...,8961581,9122254,9282927,9443600,9604273,9764946,9925619,10086292,10246965,53483
34,WEST BENGAL,68.64,69.484,70.328,71.172,72.016,72.860,73.704,74.548,75.392,...,83537654,84643148,85748643,86854137,87959631,89065126,90170620,91276115,92381609,88752